site:
  title: "Péricles Pereira - Timeline"
  description: "Bem vindo a minha timeline pessoal"
personal:
  name: "Péricles Pereira"
  avatar: "https://github.com/pericles-pereira.png"
  socialNetworks:
    github: "https://www.github.com/pericles-pereira"
    linkedin: "https://www.linkedin.com/in/pericles-pereira"
    instagram: "https://www.instagram.com/pericles_ajs/"
